name:                cataclysm-launcher-hs
version:             0.1.0.0
github:              "tlshtivo053153/cataclysm-launcher-hs"
license:             BSD-3-Clause
author:              "tlshtivo053153"
maintainer:          "muq8inubwlxpcv4oemcazmpfwowkrco-git@yahoo.co.jp"
copyright:           "2024 tlshtivo053153"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tlshtivo053153/cataclysm-launcher-hs#readme>

dependencies:
- base >= 4.7 && < 5
- monomer
- lens
- text
- text-show
- data-default
- github-rest
- vector
- aeson
- aeson-casing
- aeson-pretty
- lens-aeson
- bytestring
- safe-exceptions
- directory
- filepath
- req
- modern-uri
- zlib
- zip-archive
- conduit
- conduit-extra
- tar-conduit
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cataclysm-launcher-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cataclysm-launcher-hs

tests:
  cataclysm-launcher-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cataclysm-launcher-hs
